// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebREST_EF_50.Data;

namespace WebREST_EF_50.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210107204954_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WebREST_EF_50.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FullId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullId");

                    b.ToTable("Company");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Company");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompanyId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmployeeId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId1");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("UserId1");

                    b.ToTable("Email");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Email");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FullId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FullId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullId");

                    b.HasIndex("FullId1");

                    b.ToTable("Employee");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Objective", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FullId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FullId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FullId2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FullId3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullId");

                    b.HasIndex("FullId1");

                    b.HasIndex("FullId2");

                    b.HasIndex("FullId3");

                    b.ToTable("Objective");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Objective");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Phone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompanyId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmployeeId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId1");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("UserId1");

                    b.ToTable("Phone");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Phone");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FullId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FullId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FullId2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullId");

                    b.HasIndex("FullId1");

                    b.HasIndex("FullId2");

                    b.ToTable("Project");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Project");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Access")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Company+Full", b =>
                {
                    b.HasBaseType("WebREST_EF_50.Models.Company");

                    b.Property<long?>("HqCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("HqCompanyId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Email+Full", b =>
                {
                    b.HasBaseType("WebREST_EF_50.Models.Email");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Employee+Full", b =>
                {
                    b.HasBaseType("WebREST_EF_50.Models.Employee");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Objective+Full", b =>
                {
                    b.HasBaseType("WebREST_EF_50.Models.Objective");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Phone+Full", b =>
                {
                    b.HasBaseType("WebREST_EF_50.Models.Phone");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Project+Full", b =>
                {
                    b.HasBaseType("WebREST_EF_50.Models.Project");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.User+Full", b =>
                {
                    b.HasBaseType("WebREST_EF_50.Models.User");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Company", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.User+Full", null)
                        .WithMany("Companies")
                        .HasForeignKey("FullId");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Email", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", null)
                        .WithMany("Emails")
                        .HasForeignKey("CompanyId1");

                    b.HasOne("WebREST_EF_50.Models.Employee", null)
                        .WithMany("Emails")
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("WebREST_EF_50.Models.User", null)
                        .WithMany("Emails")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Employee", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company+Full", null)
                        .WithMany("Employees")
                        .HasForeignKey("FullId");

                    b.HasOne("WebREST_EF_50.Models.User+Full", null)
                        .WithMany("Employees")
                        .HasForeignKey("FullId1");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Objective", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company+Full", null)
                        .WithMany("Objectives")
                        .HasForeignKey("FullId");

                    b.HasOne("WebREST_EF_50.Models.Employee+Full", null)
                        .WithMany("Objectives")
                        .HasForeignKey("FullId1");

                    b.HasOne("WebREST_EF_50.Models.Project+Full", null)
                        .WithMany("Objectives")
                        .HasForeignKey("FullId2");

                    b.HasOne("WebREST_EF_50.Models.User+Full", null)
                        .WithMany("Objectives")
                        .HasForeignKey("FullId3");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Phone", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", null)
                        .WithMany("Phones")
                        .HasForeignKey("CompanyId1");

                    b.HasOne("WebREST_EF_50.Models.Employee", null)
                        .WithMany("Phones")
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("WebREST_EF_50.Models.User", null)
                        .WithMany("Phones")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Project", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company+Full", null)
                        .WithMany("Projects")
                        .HasForeignKey("FullId");

                    b.HasOne("WebREST_EF_50.Models.Employee+Full", null)
                        .WithMany("Projects")
                        .HasForeignKey("FullId1");

                    b.HasOne("WebREST_EF_50.Models.User+Full", null)
                        .WithMany("Projects")
                        .HasForeignKey("FullId2");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Company+Full", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", "HqCompany")
                        .WithMany()
                        .HasForeignKey("HqCompanyId");

                    b.HasOne("WebREST_EF_50.Models.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId");

                    b.Navigation("HqCompany");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Email+Full", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WebREST_EF_50.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("WebREST_EF_50.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Employee+Full", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WebREST_EF_50.Models.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId");

                    b.Navigation("Company");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Objective+Full", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WebREST_EF_50.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("WebREST_EF_50.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("WebREST_EF_50.Models.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Phone+Full", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WebREST_EF_50.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("WebREST_EF_50.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Project+Full", b =>
                {
                    b.HasOne("WebREST_EF_50.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WebREST_EF_50.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("WebREST_EF_50.Models.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Company", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Employee", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.User", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Company+Full", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Objectives");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Employee+Full", b =>
                {
                    b.Navigation("Objectives");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.Project+Full", b =>
                {
                    b.Navigation("Objectives");
                });

            modelBuilder.Entity("WebREST_EF_50.Models.User+Full", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Employees");

                    b.Navigation("Objectives");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
